backend:
  name: git-gateway
  branch: main
  # IMPORTANT: replace REPLACE_WITH_YOUR_NETLIFY_SITE with your Netlify site name
  identity_url: https://closet-api-towards.netlify.app/.netlify/identity
  gateway_url: https://closet-api-towards.netlify.app/.netlify/git

local_backend: true

media_folder: "uploads"
public_folder: "/uploads"

publish_mode: editorial_workflow

collections:
  - name: "entries"
    label: "Entries"
    label_singular: "Entry"
    description: "Canvas items"
    editor:
      preview: false
    files:
      - name: "entries"
        label: "Entries JSON"
        file: "entries.json"
        format: "json"
        fields:
          - { label: "Entries", name: "root", widget: "list", label_singular: "Entry", collapsed: true, summary: "{{fields.title}} · {{fields.type}}", fields: [
              { label: "Type", name: "type", widget: "select", options: ["image","text","link","text_link","youtube"] },
              { label: "Title", name: "title", widget: "string", required: false },
              { label: "Text", name: "text", widget: "text", required: false },
              { label: "URL", name: "url", widget: "string", required: false },
              { label: "Link Text", name: "linkText", widget: "string", required: false },
              { label: "Image src", name: "src", widget: "image", required: false },
              { label: "Alt", name: "alt", widget: "string", required: false },
              { label: "YouTube ID", name: "youtubeId", widget: "string", required: false },
              { label: "Tags", name: "tags", widget: "relation", required: false, collection: "tags", multiple: true, search_fields: ["name"], value_field: "name", display_fields: ["name"], allow_add: true },
              { label: "ID", name: "id", widget: "string", required: false, hint: "Optional. Leave blank to auto-generate a stable ID." },
              { label: "X", name: "x", widget: "number", required: false, hint: "Optional. Leave blank for auto-placement." },
              { label: "Y", name: "y", widget: "number", required: false, hint: "Optional. Leave blank for auto-placement." }
            ] }

  - name: "tags"
    label: "Tags"
    label_singular: "Tag"
    folder: "tags"
    create: true
    identifier_field: name
    slug: "{{slug}}"
    format: "json"
    fields:
      - { label: "Name", name: "name", widget: "string" }


